version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8085:8085"
    depends_on:
      - config-server
      - eureka-server
      # - keycloak

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.0.1
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:7.0.1
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   ports:
  #     - "9092:9092"

  # keycloak:
  #   image: quay.io/keycloak/keycloak:22.0.1
  #   container_name: keycloak
  #   command: start-dev
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports:
  #     - "8080:8080"

  service-marque:
    build:
      context: ./service-marque
    container_name: service-marque
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
      - mysql
      # - kafka
      # - keycloak

  service-article:
    build:
      context: ./service-article
    container_name: service-article
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
      - mysql
      # - kafka
      # - keycloak

volumes:
  mysql_data:
